language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
notifications:
  email: false
before_script:
  - yarn global add @angular/cli
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
- ng lint
- ng build --prod
- ng test --watch=false --browsers=ChromeHeadless