language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
notifications:
  email: false
env:
  - LANTERN_GRAFANA_URL="http://ec2-3-228-127-99.compute-1.amazonaws.com/d-solo/TFdlCHJWk/lantern-dashboard?orgId=1&refresh=10s&theme=light"
before_script:
  - npm install -g @angular/cli
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
- ng lint
- ng build --prod
- ng test --watch=false --browsers=ChromeHeadless