version: '3'

services:
  front-end:
    container_name: lantern_front_end
    build: 
      context: .
      args:
        certs: --certs
    volumes:
      - ./certs/:/usr/local/share/ca-certificates/
    ports:
      - "8090:80"
